/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alcoholic_leaf_MainJni */

#ifndef _Included_org_alcoholic_leaf_MainJni
#define _Included_org_alcoholic_leaf_MainJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_alcoholic_leaf_MainJni
 * Method:    Analysis
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_alcoholic_leaf_MainJni_Analysis
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
